
package com.services.app.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PersonsEndpoint", targetNamespace = "http://pagination.services.com", wsdlLocation = "http://localhost:8080/pagination-service/PersonsEndpoint?wsdl")
public class PersonsEndpoint
    extends Service
{

    private final static URL PERSONSENDPOINT_WSDL_LOCATION;
    private final static WebServiceException PERSONSENDPOINT_EXCEPTION;
    private final static QName PERSONSENDPOINT_QNAME = new QName("http://pagination.services.com", "PersonsEndpoint");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/pagination-service/PersonsEndpoint?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PERSONSENDPOINT_WSDL_LOCATION = url;
        PERSONSENDPOINT_EXCEPTION = e;
    }

    public PersonsEndpoint() {
        super(__getWsdlLocation(), PERSONSENDPOINT_QNAME);
    }

    public PersonsEndpoint(WebServiceFeature... features) {
        super(__getWsdlLocation(), PERSONSENDPOINT_QNAME, features);
    }

    public PersonsEndpoint(URL wsdlLocation) {
        super(wsdlLocation, PERSONSENDPOINT_QNAME);
    }

    public PersonsEndpoint(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PERSONSENDPOINT_QNAME, features);
    }

    public PersonsEndpoint(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PersonsEndpoint(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PersonEndpoint
     */
    @WebEndpoint(name = "PersonEndpointPort")
    public PersonEndpoint getPersonEndpointPort() {
        return super.getPort(new QName("http://pagination.services.com", "PersonEndpointPort"), PersonEndpoint.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PersonEndpoint
     */
    @WebEndpoint(name = "PersonEndpointPort")
    public PersonEndpoint getPersonEndpointPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://pagination.services.com", "PersonEndpointPort"), PersonEndpoint.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PERSONSENDPOINT_EXCEPTION!= null) {
            throw PERSONSENDPOINT_EXCEPTION;
        }
        return PERSONSENDPOINT_WSDL_LOCATION;
    }

}
