
package com.services.app.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PersonEndpoint", targetNamespace = "http://pagination.services.com")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PersonEndpoint {


    /**
     * 
     * @param pageSize
     * @param pageNumber
     * @return
     *     returns com.services.app.client.Page
     */
    @WebMethod
    @WebResult(targetNamespace = "http://pagination.services.com")
    @RequestWrapper(localName = "getPersonsPage", targetNamespace = "http://pagination.services.com", className = "com.services.app.client.GetPersonsPage")
    @ResponseWrapper(localName = "getPersonsPageResponse", targetNamespace = "http://pagination.services.com", className = "com.services.app.client.GetPersonsPageResponse")
    public Page getPersonsPage(
        @WebParam(name = "pageSize", targetNamespace = "")
        int pageSize,
        @WebParam(name = "pageNumber", targetNamespace = "")
        int pageNumber);

}
